# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI/CalculatorDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(547, 300)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(30, 240, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.lineEdit_Factor1 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_Factor1.setGeometry(QtCore.QRect(10, 10, 201, 29))
        self.lineEdit_Factor1.setObjectName("lineEdit_Factor1")
        self.lineEdit_Factor2 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_Factor2.setGeometry(QtCore.QRect(309, 10, 191, 29))
        self.lineEdit_Factor2.setObjectName("lineEdit_Factor2")
        self.comboBox_Operand = QtWidgets.QComboBox(Dialog)
        self.comboBox_Operand.setGeometry(QtCore.QRect(220, 10, 80, 29))
        self.comboBox_Operand.setObjectName("comboBox_Operand")
        self.listView_Results = QtWidgets.QListView(Dialog)
        self.listView_Results.setGeometry(QtCore.QRect(240, 40, 256, 192))
        self.listView_Results.setObjectName("listView_Results")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
